### PR TITLE
Add/improve ComposeT instances with `QuantifiedConstraints`

### PR DESCRIPTION
**Pull request by baskaransri**
Adding MFunctor and improving MonadTrans for ComposeT with code from issue #4

### CODE REVIEW

**Comment by Gabriel439** [comment]
Actually, based on discussion here:

* https://github.com/Gabriel439/Haskell-MMorph-Library/issues/4#issuecomment-450671035

... I think it might be better to only add the `MFunctor` instance to and to leave the `MonadTrans` instance as is.   Would that be okay?

**Comment by naraksab** [comment]
Would you want the MFunctor instance to be GHC-version gated on
`__GLASGOW_HASKELL__ >= 806`, providing different interfaces for different versions, or just have a unified interface?

**Comment by baskaransri** [comment]
Would you want the MFunctor instance to be GHC-version gated on
`__GLASGOW_HASKELL__ >= 806`, providing different interfaces for different versions, or just have a unified interface?

**Comment by Gabriel439** [comment]
@baskaransri: A version gate for the `MFunctor` instance is fine

**Comment by Gabriel439** [comment]
Closing as I believe this was superseded by #40

**Pull request closed without merging**
