### PR TITLE
PolyKinded MFunctor.

### PR DESCRIPTION
**Pull request by jkarni**

### CODE REVIEW

**Comment by jkarni** [comment]
Fixes #29.

My editor removes trailing whitespace, but I can undo that if you'd prefer minimal diffs.

**Comment by Gabriel439** [comment]
No problem at all!  Whitespace changes are fine

Thank you for the contribution :)

**Comment by treeowl** [comment]
@Gabriel439 I don't see how this does anything whatsoever. As far as I can tell, nothing here *can* be poly-kinded. Am I missing something?

**Comment by fizruk** [comment]
@treeowl compare

```haskell
class MFunctor (t :: (* -> *) -> * -> *)
```

vs

```haskell
class MFunctor (t :: (k -> *) -> k -> *)
```

**Comment by treeowl** [comment]
Ah, it's not quite as general as you said (it's actually

class MFunctor (t :: (* -> *) -> k -> *)


But I was definitely wrong.

On May 16, 2017 3:27 AM, "Nickolay Kudasov" <notifications@github.com>
wrote:

@treeowl <https://github.com/treeowl> compare

class MFunctor (t :: (* -> *) -> * -> *)

vs

class MFunctor (t :: (k -> *) -> k -> *)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Gabriel439/Haskell-MMorph-Library/pull/30#issuecomment-301698919>,
or mute the thread

**Pull request merged**
